"""empty message

Revision ID: aa47193f3625
Revises: 4e5864da6efe
Create Date: 2017-06-17 13:40:20.124366

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa47193f3625'
down_revision = '4e5864da6efe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('about_me', sa.Text(), nullable=True))
    op.add_column('roles', sa.Column('location', sa.String(length=64), nullable=True))
    op.add_column('roles', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'member_since')
    op.drop_column('roles', 'location')
    op.drop_column('roles', 'about_me')
    # ### end Alembic commands ###
